ccc

diff --git a/.github/workflows/var2.yml b/.github/workflows/var2.yml
--- a/.github/workflows/var2.yml
+++ b/.github/workflows/var2.yml
@@ -320,77 +320,84 @@ jobs:
                echo "### 💀 ${{ matrix.file }}" >> $GITHUB_STEP_SUMMARY
                echo "${{ matrix.file }}" >> results/log-${{ matrix.file }}
             fi
-            echo "Trying again"
-            if timeout "$TIMEOUT"m echo y | am -i "${{ matrix.file }}" --debug 2>&1 | tee -a results/log-"${{ matrix.file }}"; then
-              # Blacklist some applications
-              # removed 'swift' because will flag swifty which is working
-              if [[ "$pure_arg" =~ (bat-extras|code$|microsoft-edge*|node$|npm|oras) ]]; then
-                echo "This app is blacklisted due to known errors related to GitHub Actions" | tee -a results/log-"${{ matrix.file }}"
-              else
-                # Check if the app needs interaction to be installed
-                if [[ "$pure_arg" =~ (libreoffice|mpv|wine) ]]; then
-                  echo 1 | am -i "${{ matrix.file }}" --debug 2>&1
-                  LASTDIR=$(ls -td /opt/* | head -1 | sed 's:.*/::')
-                  if ! test -f /opt/"$LASTDIR"/remove; then
-                    sudo systemctl restart tor.service || systemctl restart tor.service
-                    echo 1 | torsocks am -i "${{ matrix.file }}" --debug 2>&1
-                  fi
-                fi
-                # Force installation if first attempt is not success
+          fi
+
+      - name: "second try"
+        if: failure()
+        run: |
+          echo "Trying again"
+          if timeout "$TIMEOUT"m echo y | am -i "${{ matrix.file }}" --debug 2>&1 | tee -a results/log-"${{ matrix.file }}"; then
+            # Blacklist some applications
+            # removed 'swift' because will flag swifty which is working
+            if [[ "$pure_arg" =~ (bat-extras|code$|microsoft-edge*|node$|npm|oras) ]]; then
+              echo "This app is blacklisted due to known errors related to GitHub Actions" | tee -a results/log-"${{ matrix.file }}"
+            else
+              # Check if the app needs interaction to be installed
+              if [[ "$pure_arg" =~ (libreoffice|mpv|wine) ]]; then
+                echo 1 | am -i "${{ matrix.file }}" --debug 2>&1
                 LASTDIR=$(ls -td /opt/* | head -1 | sed 's:.*/::')
                 if ! test -f /opt/"$LASTDIR"/remove; then
                   sudo systemctl restart tor.service || systemctl restart tor.service
-                  am -i "${{ matrix.file }}" --debug 2>&1
+                  echo 1 | torsocks am -i "${{ matrix.file }}" --debug 2>&1
+                fi
+              fi
+              # Force installation if first attempt is not success
+              LASTDIR=$(ls -td /opt/* | head -1 | sed 's:.*/::')
+              if ! test -f /opt/"$LASTDIR"/remove; then
+                sudo systemctl restart tor.service || systemctl restart tor.service
+                am -i "${{ matrix.file }}" --debug 2>&1
+                LASTDIR=$(ls -td /opt/* | head -1 | sed 's:.*/::')
+                if ! test -f /opt/"$LASTDIR"/remove; then
+                  sudo systemctl restart tor.service || systemctl restart tor.service
+                  torsocks am -i "${{ matrix.file }}" --debug 2>&1
                   LASTDIR=$(ls -td /opt/* | head -1 | sed 's:.*/::')
-                  if ! test -f /opt/"$LASTDIR"/remove; then
-                    sudo systemctl restart tor.service || systemctl restart tor.service
-                    torsocks am -i "${{ matrix.file }}" --debug 2>&1
-                    LASTDIR=$(ls -td /opt/* | head -1 | sed 's:.*/::')
-                  fi
                 fi
-                if [ "$LASTDIR" = am ]; then
-                  exit 1
-                fi
-                printf "\n-------------------------------------------------------------\n\n"
-                # Check structure of directories in /opt
-                echo " Structure of the directory in /opt"
-                echo ""
-                if test -f /opt/"$LASTDIR"/remove; then
-                   ls /opt/"$LASTDIR" | tee -a results/log-"${{ matrix.file }}"
-                else
-                   exit 1
-                fi
-                printf "\n-------------------------------------------------------------\n\n"
-                # Check the command in /usr/local/bin
-                echo " Command in \$PATH"
-                echo ""
-                command -v "$pure_arg" | tee -a results/log-"${{ matrix.file }}" || command -v "$LASTDIR" | tee -a results/log-"${{ matrix.file }}" || ls /usr/local/bin | tee -a results/log-"${{ matrix.file }}"
-                printf "\n-------------------------------------------------------------\n\n"
-                # Check launchers in /usr/local/share/applications
-                echo " Launchers in /usr/local/share/applications" | tee -a results/log-"${{ matrix.file }}"
-                echo ""
-                if test -f /usr/local/share/applications/*AM.desktop 2>/dev/null; then
-                   ls /usr/local/share/applications | grep "AM.desktop$" | tee -a results/log-"${{ matrix.file }}"
-                else
-                   ls /usr/local/share/applications | tee -a results/log-"${{ matrix.file }}"
-                fi
-                printf "\n-------------------------------------------------------------\n\n"
-                # Remove the application
-                am -R "$LASTDIR" && echo "${{ matrix.file }}" >> results/ok-${{ matrix.file }} || echo "${{ matrix.file }}" >> results/log-${{ matrix.file }}
               fi
-            else
-              # Determine timeout
-              if [[ $? -eq 124 ]]; then
-                 echo "### 💥 ${{ matrix.file }} $TIMEOUT minutes timeout reached" >> $GITHUB_STEP_SUMMARY
-                 echo "Installation timeout in $TIMEOUT minutes" >> results/log-"${{ matrix.file }}"
-                 echo "${{ matrix.file }}" >> results/log-${{ matrix.file }}
+              if [ "$LASTDIR" = am ]; then
+                exit 1
+              fi
+              printf "\n-------------------------------------------------------------\n\n"
+              # Check structure of directories in /opt
+              echo " Structure of the directory in /opt"
+              echo ""
+              if test -f /opt/"$LASTDIR"/remove; then
+                 ls /opt/"$LASTDIR" | tee -a results/log-"${{ matrix.file }}"
               else
-                 echo "### 💀 ${{ matrix.file }}" >> $GITHUB_STEP_SUMMARY
-                 echo "${{ matrix.file }}" >> results/log-${{ matrix.file }}
+                 exit 1
               fi
-              exit 1
+              printf "\n-------------------------------------------------------------\n\n"
+              # Check the command in /usr/local/bin
+              echo " Command in \$PATH"
+              echo ""
+              command -v "$pure_arg" | tee -a results/log-"${{ matrix.file }}" || command -v "$LASTDIR" | tee -a results/log-"${{ matrix.file }}" || ls /usr/local/bin | tee -a results/log-"${{ matrix.file }}"
+              printf "\n-------------------------------------------------------------\n\n"
+              # Check launchers in /usr/local/share/applications
+              echo " Launchers in /usr/local/share/applications" | tee -a results/log-"${{ matrix.file }}"
+              echo ""
+              if test -f /usr/local/share/applications/*AM.desktop 2>/dev/null; then
+                 ls /usr/local/share/applications | grep "AM.desktop$" | tee -a results/log-"${{ matrix.file }}"
+              else
+                 ls /usr/local/share/applications | tee -a results/log-"${{ matrix.file }}"
+              fi
+              printf "\n-------------------------------------------------------------\n\n"
+              # Remove the application
+              am -R "$LASTDIR" && echo "${{ matrix.file }}" >> results/ok-${{ matrix.file }} || echo "${{ matrix.file }}" >> results/log-${{ matrix.file }}
             fi
+          else
+            # Determine timeout
+            if [[ $? -eq 124 ]]; then
+               echo "### 💥 ${{ matrix.file }} $TIMEOUT minutes timeout reached" >> $GITHUB_STEP_SUMMARY
+               echo "Installation timeout in $TIMEOUT minutes" >> results/log-"${{ matrix.file }}"
+               echo "${{ matrix.file }}" >> results/log-${{ matrix.file }}
+            else
+               echo "### 💀 ${{ matrix.file }}" >> $GITHUB_STEP_SUMMARY
+               echo "${{ matrix.file }}" >> results/log-${{ matrix.file }}
+            fi
+            exit 1
           fi
+
+      - name: "Finish output"
+        run: |
           size=$(cat results/log-${{ matrix.file }} | grep 'OF DISK SPACE' | cut -d'(' -f2 | cut -d' ' -f1,2)
           version=$(cat results/log-${{ matrix.file }} | grep '◆' | tail -1)
           echo "size=${size}" | tee -a results/out-"${{ matrix.file }}"
